name: internship-management-system

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: internship_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d internship_management"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    environment:
      APP_PORT: "8080"
      FRONTEND_ORIGIN: http://localhost:4200
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: internship_management
      DB_SSLMODE: disable
      JWT_SECRET: development-only-secret-change-me
      JWT_EXPIRES_HOURS: "24"
      UPLOAD_DIR: /data/uploads
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - final_reports:/data/uploads

  pgadmin:
    image: dpage/pgadmin4:9.14
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@internship-management.com
      PGADMIN_DEFAULT_PASSWORD: Demo123!
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
  final_reports:
